import {liveMode} from '../services/backendClient';
import {useLiveCampusViewModel} from './useLiveCampusViewModel';
import { Permission, defaultPermissions } from '../models/permissions';
'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { CampusState, Role, Status, seed, health } from '../models/campus';
import { CampusRepository, demoRepository } from '../services/campusRepository';
import { toast } from 'sonner';
import { validCoordinates } from '../models/mapConfig';
function useDemoCampusViewModel(repository:CampusRepository=demoRepository) {
 const [data,setData]=useState<CampusState>(seed); const [ready,setReady]=useState(false);
 const [role,setRole]=useState<Role>('Student'); const [page,setPage]=useState('Dashboard');
 const [building,setBuilding]=useState('All buildings'); const [query,setQuery]=useState('');
 const [locationId,setLocationId]=useState('LIB-F2-01'); const [progress,setProgress]=useState(0); const [running,setRunning]=useState(false);
 const [lastTestId,setLastTestId]=useState(''); const [range,setRange]=useState('Today');
 const timer=useRef<ReturnType<typeof setInterval>|null>(null);
 useEffect(()=>{try{setData(repository.load());}catch{toast.error('Unable to load saved campus data',{description:'The demo workspace is available. Refresh to try loading your saved data again.'});}setReady(true);},[repository]);
 useEffect(()=>{if(ready) try {repository.save(data);} catch {toast.error('Unable to save changes',{id:'storage-failure',description:'Your changes are available in this session but may be lost after refresh. Check browser storage and try again.'});}},[data,ready,repository]);
 useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);},[]);
 const locations=useMemo(()=>data.locations.filter(l=>(building==='All buildings'||l.building===building)&&`${l.name} ${l.building}`.toLowerCase().includes(query.toLowerCase())),[data.locations,building,query]);
 const complaints=useMemo(()=>data.complaints.filter(c=>(role!=='Student'||c.owner==='student-demo')&&locations.some(l=>l.id===c.locationId)),[data.complaints,role,locations]);
 const location=data.locations.find(l=>l.id===locationId)||data.locations[0];
 const lastTest=data.tests.find(t=>t.id===lastTestId);
 const switchRole=(r:Role)=>{setRole(r);setPage('Dashboard');setBuilding('All buildings');setQuery('');};
 function feedback(kind:'success'|'error'|'info',message:string,recipients:Role[]=[role]){toast[kind](message,{duration:kind==='error'?7000:4500});setData(d=>({...d,alerts:[{id:crypto.randomUUID(),message,kind,createdAt:new Date().toISOString(),recipients,readBy:[]},...(d.alerts||[])].slice(0,200)}));}
 const alerts=(data.alerts||[]).filter(a=>a.recipients.includes(role));const unreadAlerts=alerts.filter(a=>!a.readBy.includes(role)).length;
 function markAlertsRead(){setData(d=>({...d,alerts:(d.alerts||[]).map(a=>a.recipients.includes(role)&&!a.readBy.includes(role)?{...a,readBy:[...a.readBy,role]}:a)}));toast.success('Notifications marked as read.');}
 function runTest(){ if(running)return;if(!location.tests){feedback('error','Test unavailable for this location. No measurement service is connected yet; choose a location with demo results.');return;}feedback('info','Connection test started. Keep this page open until the test completes.');setLastTestId('');setProgress(0);setRunning(true);let p=0;const selected=location;
 timer.current=setInterval(()=>{p+=5;setProgress(p);if(p>=100){if(timer.current)clearInterval(timer.current);timer.current=null;setRunning(false);const t={id:crypto.randomUUID(),locationId:selected.id,download:selected.download,upload:selected.upload,ping:selected.ping,score:selected.score,testedAt:new Date().toISOString(),simulated:true as const};setData(d=>({...d,tests:[t,...d.tests]}));setLastTestId(t.id);feedback('success','Connection test completed. Your demo result is available in Test History.');}},150); }
 function cancelTest(){if(timer.current)clearInterval(timer.current);timer.current=null;setRunning(false);setProgress(0);feedback('info','Test cancelled. No result was saved.');}
 function submitComplaint(category:string,description:string,selectedLocation:string,includeTest:boolean){if(!data.locations.some(l=>l.id===selectedLocation)){feedback('error','Select a valid campus location before submitting your complaint.');return false;}if(description.trim().length<10||description.trim().length>500){feedback('error','Describe the issue in at least 10 characters.');return false;}const c={id:`SC-${Date.now().toString().slice(-7)}`,locationId:selectedLocation,category,description:description.trim(),status:'Open' as Status,assignee:'Unassigned',createdAt:new Date().toISOString(),owner:'student-demo',notes:includeTest&&lastTest&&lastTest.locationId===selectedLocation?[`Attached simulated test: ${lastTest.download} Mbps down, ${lastTest.ping} ms RTT.`]:[]};setData(d=>({...d,complaints:[c,...d.complaints]}));feedback('success',`Complaint ${c.id} submitted. IT Support can now review your report.`,['Student','IT Support','Manager','Administrator']);return true;}
 function updateComplaint(id:string,status:Status,assignee:string,note:string){const target=data.complaints.find(c=>c.id===id);if(role!=='IT Support'||!can('complaints')||!target){feedback('error','Unable to update this complaint. Check your permissions and refresh the report.');return false;}if(status!=='Open'&&assignee==='Unassigned'){feedback('error','Select an IT staff member before assigning or progressing this complaint.');return false;}if(status==='Resolved'&&note.trim().length<10){feedback('error','Add a resolution note of at least 10 characters explaining the repair and verification.');return false;}setData(d=>({...d,supportActivities:[{id:crypto.randomUUID(),complaintId:id,locationId:target.locationId,status,assignee,actor:'Sarah Khan',note:note.trim(),createdAt:new Date().toISOString()},...(d.supportActivities||[])],complaints:d.complaints.map(c=>c.id===id?{...c,status,assignee,notes:[...c.notes,`${status} · ${assignee}${note.trim()?` — ${note.trim()}`:''}`]}:c)}));feedback('success',`Complaint ${id} ${status==='Resolved'?'resolved':status==='Assigned'?'assigned to '+assignee:status==='In Progress'?'is now in progress':'updated'}.`,['Student','IT Support','Manager','Administrator']);return true;}
 function addLocation(name:string,b:string,floor:string,latitude?:number,longitude?:number){if(!name.trim()||!b.trim()){feedback('error','Enter a location and building name.');return false;}if((latitude!==undefined||longitude!==undefined)&&!validCoordinates(latitude,longitude)){feedback('error','Enter valid latitude and longitude, or leave both blank.');return false;}setData(d=>({...d,locations:[...d.locations,{id:crypto.randomUUID(),name:name.trim(),building:b.trim(),floor:floor.trim()||'Ground floor',score:0,download:0,upload:0,ping:0,tests:0,x:0,y:0,latitude,longitude,coordinateSource:latitude!==undefined?'manual':undefined}]}));feedback('success','Location added. Health is unknown until measured.');return true;}
 function addCustomLocation(name:string,latitude:number,longitude:number){const clean=name.trim();if(clean.length<2||clean.length>80||!validCoordinates(latitude,longitude)){feedback('error','Enter a name of 2–80 characters and select a valid map position.');return null;}const id=crypto.randomUUID();setData(d=>({...d,locations:[...d.locations,{id,name:clean,building:'Custom locations',floor:'User-reported location',latitude,longitude,coordinateSource:'manual',userReported:true,score:0,download:0,upload:0,ping:0,tests:0,x:0,y:0}]}));feedback('success','Custom location saved and selected.');return id;}
 function addMaintenanceNote(locationId:string,text:string){if(role!=='IT Support'||!can('maintenance')||!data.locations.some(l=>l.id===locationId)||text.trim().length<10||text.trim().length>1000){feedback('error','Choose a location and enter a maintenance note of 10–1000 characters.');return false;}setData(d=>({...d,maintenanceNotes:[{id:crypto.randomUUID(),locationId,text:text.trim(),author:'Sarah Khan',createdAt:new Date().toISOString()},...(d.maintenanceNotes||[])]}));feedback('success','Maintenance note saved.');return true;}
 function updateLocation(id:string,name:string,buildingName:string,floor:string,latitude:number,longitude:number){if(role!=='Administrator'||!data.locations.some(l=>l.id===id)){feedback('error','Unable to edit this location. Administrator access and a valid location are required.');return false;}if(name.trim().length<2||name.trim().length>80||!buildingName.trim()||buildingName.trim().length>80||floor.trim().length>40||!validCoordinates(latitude,longitude)){feedback('error','Enter a location name, building, and valid map position.');return false;}setData(d=>({...d,locations:d.locations.map(l=>l.id===id?{...l,name:name.trim(),building:buildingName.trim(),floor:floor.trim()||'Ground floor',latitude,longitude,coordinateSource:'manual' as const}:l)}));feedback('success','Campus location updated.');return true;}
 function updateCoordinates(id:string,latitude:number,longitude:number){if(!validCoordinates(latitude,longitude)){feedback('error','Latitude must be −90 to 90; longitude must be −180 to 180.');return false;}setData(d=>({...d,locations:d.locations.map(l=>l.id===id?{...l,latitude,longitude,coordinateSource:'manual' as const}:l)}));feedback('success','Location coordinates saved.');return true;}
 function can(permission:Permission){return (data.permissions?.[role]||defaultPermissions[role]).includes(permission);}
 function changeUserRole(id:string,next:Role){if(role!=='Administrator'||!['Student','IT Support','Manager'].includes(next)||id==='admin-demo'){feedback('error','Unable to change this role. The administrator account is protected.');return false;}setData(d=>({...d,users:d.users.map(u=>u.id===id?{...u,role:next}:u)}));feedback('success',`User role changed to ${next}.`);return true;}
 function savePermissions(target:Role,permissions:Permission[]){if(role!=='Administrator'||!['IT Support','Manager'].includes(target)){feedback('error','Administrator access is required to manage role permissions.');return;}setData(d=>({...d,permissions:{...d.permissions,[target]:permissions}}));feedback('success',`Permissions saved for ${target}.`);}
 function setThresholds(good:number,excellent:number){if(role!=='Administrator'||!Number.isInteger(good)||!Number.isInteger(excellent)||good<50||good>99||excellent>100||excellent<=good){feedback('error','Good must be at least 50; excellent must be higher and at most 100.');return false;}setData(d=>({...d,thresholds:{good,excellent}}));feedback('success','Network health thresholds saved. Status labels now use the updated bands.');return true;}
 function toggleUser(id:string){if(role!=='Administrator'||id==='admin-demo'){feedback('error','Unable to change account status. The administrator account is protected.');return;}setData(d=>({...d,users:d.users.map(u=>u.id===id?{...u,active:!u.active}:u)}));feedback('success',`Account ${data.users.find(u=>u.id===id)?.active?'deactivated':'activated'}.`);}
 function exportReport(){try{if(!can('reports')){feedback('error','Your role does not have report export permission.');return;}const rows=[['Building','Location','Health','Download Mbps','Upload Mbps','RTT ms','Samples'],...locations.map(l=>[l.building,l.name,l.tests?health(l.score,data.thresholds):'Unknown',l.download,l.upload,l.ping,l.tests])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='smart-campus-demo-report.csv';a.click();URL.revokeObjectURL(url);feedback('success','Report download started. Check your browser downloads.');}catch{feedback('error','Unable to generate the report. Please try again.');}}
 return {data,ready,role,switchRole,page,setPage,building,setBuilding,query,setQuery,range,setRange,locations,complaints,locationId,setLocationId,location,progress,running,lastTest,runTest,cancelTest,submitComplaint,updateComplaint,addLocation,addCustomLocation,addMaintenanceNote,updateLocation,updateCoordinates,feedback,alerts,unreadAlerts,markAlertsRead,setThresholds,toggleUser,changeUserRole,savePermissions,can,exportReport};
}
export type CampusVM=ReturnType<typeof useDemoCampusViewModel>;
export function useCampusViewModel(){return liveMode?useLiveCampusViewModel():useDemoCampusViewModel();}
