[pytest]
testpaths = tests
filterwarnings =
    ignore:cannot collect test class 'TestAttempt':pytest.PytestCollectionWarning
    ignore:cannot collect test class 'TestResult':pytest.PytestCollectionWarning
