import {Sparkles,RefreshCw,ClipboardList,Activity,MapPin,TriangleAlert} from 'lucide-react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import type {CampusVM} from '../viewmodels/useCampusViewModel';
import {useAdminAIViewModel,aiCategoryLabels} from '../viewmodels/useAdminAIViewModel';
import {liveMode} from '../services/backendClient';

function State({error,configured}:{error:string;configured?:boolean}){
 return <>{error&&<p className="ai-notice" role="alert"><TriangleAlert size={17}/>{error}</p>}
 {configured===false&&<p className="ai-notice">Gemini is not configured. Add the API key to the backend environment; classification will use clearly labelled keyword suggestions until then.</p>}</>;
}
export function ComplaintClassification({vm}:{vm:CampusVM}){
 const model=useAdminAIViewModel(vm);
 const rows=model.data?.complaints||[];
 const pending=rows.filter(c=>!c.analysis).length;
 return <section className="panel"><div className="panel-heading"><div><h2>Automatic complaint classification</h2><p>New complaints are analyzed automatically. Review the suggested category, reasoning and provider below.</p></div><button className="primary small" disabled={!liveMode||!!model.busy||!pending} onClick={model.classifyPending}><Sparkles size={15}/>{model.busy==='pending'?'Classifying…':'Classify next pending'}</button></div>
 <div className="ai-tools-meta"><span>{rows.length} recent complaints · {pending} awaiting classification</span><button className="text-btn" disabled={!!model.busy||!liveMode} onClick={model.reload}><RefreshCw size={14}/>Refresh</button></div>
 <State error={model.error} configured={model.data?.configured}/>
 <div className="table-scroll"><Table><TableHeader><TableRow>{['Complaint','Category','Classification','Reasoning','Action'].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(c=><TableRow key={c.id}>
 <TableCell><strong>{c.reference}</strong><small>{c.location}</small><p className="ai-complaint-description">{c.description}</p></TableCell>
 <TableCell><span className="badge assigned">{aiCategoryLabels[c.category]}</span>{c.analysis?.applied&&<small>Classification applied</small>}</TableCell>
 <TableCell>{c.analysis?<><strong>{aiCategoryLabels[c.analysis.category]}</strong><small>{c.analysis.method==='gemini'?'Gemini':'Keyword rules'} · {c.analysis.confidence>=.8?'High':c.analysis.confidence>=.5?'Medium':'Low'} confidence estimate</small></>:<span className="muted">Pending</span>}</TableCell>
 <TableCell><p>{c.analysis?.reason||'Awaiting analysis.'}</p>{c.analysis?.warning&&<small className="ai-warning">{c.analysis.warning}</small>}</TableCell>
 <TableCell><div className="ai-row-actions"><button className="outline-link" disabled={!!model.busy||!liveMode} onClick={()=>model.classify(c.id)}>{model.busy===c.id?'Processing…':c.analysis?'Reclassify':'Classify'}</button>{c.analysis&&c.category!==c.analysis.category&&<button className="outline-link" disabled={!!model.busy||!liveMode} onClick={()=>model.apply(c.id)}>Use category</button>}</div></TableCell>
 </TableRow>)}</TableBody></Table></div>
 {!rows.length&&<p className="empty">{model.data?'No complaints are available to classify.':'Loading complaint classifications…'}</p>}
 <p className="ai-footnote">High-confidence Gemini categories are applied to new complaints automatically. Lower-confidence and keyword results remain suggestions for administrator review. AI confidence is an estimate.</p>
 </section>;
}
export function AINetworkSummary({vm}:{vm:CampusVM}){
 const model=useAdminAIViewModel(vm),summary=model.data?.last_summary;
 return <section className="panel"><div className="panel-heading"><div><h2>AI network summary</h2><p>Simple IT insights from recorded measurements and complaints in your campus.</p></div><div className="ai-summary-actions"><select className="picker" aria-label="AI summary period" value={model.hours} disabled={!!model.busy} onChange={e=>model.setHours(e.target.value)}><option value="24">Last 24 hours</option><option value="72">Last 3 days</option><option value="168">Last 7 days</option></select><button className="primary" disabled={!!model.busy||!liveMode} onClick={model.generate}><Sparkles size={17}/>{model.busy==='summary'?'Generating…':'Generate summary'}</button></div></div>
 <State error={model.error} configured={model.data?.configured}/>
 {summary?<div className="ai-summary-content"><div className="ai-tools-meta"><span>{summary.method==='gemini'?'Generated by Gemini':'Factual data summary'} · Last {summary.hours} hours</span><small>Generated {new Date(summary.generated_at).toLocaleString('en-GB',{timeZone:'Asia/Karachi'})}</small></div>
 {summary.warning&&<p className="ai-notice" role="status">{summary.warning}</p>}
 <div className="stats-grid ai-summary-stats">{[{label:'Recorded tests',value:summary.facts.test_count,icon:Activity},{label:'Complaints',value:summary.facts.complaint_count,icon:ClipboardList},{label:'Locations with data',value:summary.facts.locations_with_data,icon:MapPin}].map(item=><div className="stat" key={item.label}><span className="stat-icon blue"><item.icon size={20}/></span><div><p>{item.label}</p><strong>{item.value}</strong></div></div>)}</div>
 <div className="description-box"><h3>Network overview</h3><p>{summary.summary}</p></div>
 <div className="ai-insight-grid"><section><h3>Observed patterns</h3>{summary.observations.length?<ul>{summary.observations.map((text,i)=><li key={i}>{text}</li>)}</ul>:<p className="muted">No supported patterns are available in this period.</p>}</section><section><h3>Suggested IT checks</h3><ul>{summary.recommendations.map((text,i)=><li key={i}>{text}</li>)}</ul></section></div>
 {summary.limitations.length>0&&<div className="config-notice"><TriangleAlert size={18}/><div><strong>Data coverage and limitations</strong><ul>{summary.limitations.map((text,i)=><li key={i}>{text}</li>)}</ul></div></div>}
 <p className="ai-footnote">AI insights support investigation. Recommendations do not confirm a root cause or outage. Campus time: {summary.facts.timezone}.</p>
 </div>:<div className="test-empty"><Sparkles size={40}/><h3>Your network insights will appear here</h3><p>Select a period and generate a summary from your actual campus records.</p></div>}
 </section>;
}
